Repository second-hand-team-04/second-hand-max-be-b, pull requests merged in 2023-09, with the labels that each got.

#25 feat #21: oauth login 구현
  build.gradle
  src/main/java/com/codesquad/secondhand/auth/application/AuthService.java
  src/main/java/com/codesquad/secondhand/auth/application/TokenService.java
  src/main/java/com/codesquad/secondhand/auth/domain/OauthAttributes.java
  src/main/java/com/codesquad/secondhand/auth/domain/OauthUserInfomation.java
  src/main/java/com/codesquad/secondhand/auth/domain/ProviderType.java
  src/main/java/com/codesquad/secondhand/auth/domain/RefreshToken.java
  src/main/java/com/codesquad/secondhand/auth/infrastrucure/AuthRepository.java
  src/main/java/com/codesquad/secondhand/auth/infrastrucure/RefreshTokenRepository.java
  src/main/java/com/codesquad/secondhand/auth/infrastrucure/oauth/JwtTokenProvider.java
  src/main/java/com/codesquad/secondhand/auth/infrastrucure/oauth/OauthClient.java
  src/main/java/com/codesquad/secondhand/auth/infrastrucure/oauth/OauthProperties.java
  src/main/java/com/codesquad/secondhand/auth/infrastrucure/oauth/dto/OauthTokenResponse.java
  src/main/java/com/codesquad/secondhand/auth/ui/AuthController.java
  src/main/java/com/codesquad/secondhand/common/config/WebConfig.java
  src/main/java/com/codesquad/secondhand/common/interceptor/AuthInterceptor.java
  src/main/java/com/codesquad/secondhand/common/resolver/AccountPrincipalArgumentResolver.java
  src/test/java/com/codesquad/secondhand/acceptance/AuthAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/unit/domain/JwtTokenProviderTest.java
  src/test/resources/schema.sql
Labels: feature, SPRINT#3

#26 feat #24: 사용자 상세 정보 조회 기능 구현
  src/main/java/com/codesquad/secondhand/Image/domain/ImageFileDetail.java
  src/main/java/com/codesquad/secondhand/common/response/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/user/application/dto/UserInfoResponse.java
  src/main/java/com/codesquad/secondhand/user/domain/User.java
  src/main/java/com/codesquad/secondhand/user/ui/UserController.java
  src/test/java/com/codesquad/secondhand/acceptance/AuthAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/acceptance/CategoryAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/acceptance/RegionAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/acceptance/UserAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/AcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/FakeS3Client.java
  src/test/java/com/codesquad/secondhand/util/steps/UserSteps.java
Labels: feature, SPRINT#3

#28 feat #23: 유저 프로필 수정 기능 구현
  src/main/java/com/codesquad/secondhand/common/config/WebConfig.java
  src/main/java/com/codesquad/secondhand/common/interceptor/AuthInterceptor.java
  src/main/java/com/codesquad/secondhand/common/response/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/item/application/ItemService.java
  src/main/java/com/codesquad/secondhand/user/application/UserService.java
  src/main/java/com/codesquad/secondhand/user/application/dto/UserUpdateRequest.java
  src/main/java/com/codesquad/secondhand/user/domain/User.java
  src/main/java/com/codesquad/secondhand/user/infrastructure/UserRepository.java
  src/main/java/com/codesquad/secondhand/user/ui/UserController.java
  src/test/java/com/codesquad/secondhand/acceptance/UserAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/unit/domain/UserTest.java
  src/test/java/com/codesquad/secondhand/util/fixture/ImageFixture.java
  src/test/java/com/codesquad/secondhand/util/fixture/ItemImageFixture.java
  src/test/java/com/codesquad/secondhand/util/fixture/StatusFixture.java
  src/test/java/com/codesquad/secondhand/util/steps/UserSteps.java
Labels: feature, SPRINT#3

#33 fix #32: GlobalHandlerException CRLF 수정
  src/main/java/com/codesquad/secondhand/common/exception/GlobalExceptionHandler.java
Labels: fix, SPRINT#3

#36 feat #22: 상품 등록 기능 구현
  src/main/java/com/codesquad/secondhand/Image/application/ImageService.java
  src/main/java/com/codesquad/secondhand/category/application/CategoryService.java
  src/main/java/com/codesquad/secondhand/common/exception/ErrorType.java
  src/main/java/com/codesquad/secondhand/common/exception/category/CategoryNotFoundException.java
  src/main/java/com/codesquad/secondhand/common/exception/item/ItemImageEmptyException.java
  src/main/java/com/codesquad/secondhand/common/exception/item/ItemImageMaxAddCountException.java
  src/main/java/com/codesquad/secondhand/common/exception/item/StatusNotFoundException.java
  src/main/java/com/codesquad/secondhand/common/response/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/item/application/ItemService.java
  src/main/java/com/codesquad/secondhand/item/application/dto/ItemCreateRequest.java
  src/main/java/com/codesquad/secondhand/item/domain/Images.java
  src/main/java/com/codesquad/secondhand/item/domain/Item.java
  src/main/java/com/codesquad/secondhand/item/domain/ItemImage.java
  src/main/java/com/codesquad/secondhand/item/domain/StatusType.java
  src/main/java/com/codesquad/secondhand/item/infrastructure/ItemDaoImpl.java
  src/main/java/com/codesquad/secondhand/item/infrastructure/ItemRepository.java
  src/main/java/com/codesquad/secondhand/item/infrastructure/StatusRepository.java
  src/main/java/com/codesquad/secondhand/item/ui/ItemController.java
  src/test/java/com/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/steps/ItemSteps.java
  src/test/resources/schema.sql
Labels: feature, SPRINT#3

#38 feat #22: 상품 등록 기능 구현 PR 리뷰 반영
  src/main/java/com/codesquad/secondhand/common/response/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/item/application/ItemService.java
  src/main/java/com/codesquad/secondhand/item/application/StatusService.java
  src/main/java/com/codesquad/secondhand/item/application/dto/ItemCreateRequest.java
  src/main/java/com/codesquad/secondhand/item/domain/Images.java
  src/main/java/com/codesquad/secondhand/item/domain/Item.java
  src/test/java/com/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/fixture/ImageFixture.java
Labels: fix, SPRINT#3

#40 feat #37: 나의 판매내역 조회 기능 구현
  src/main/java/com/codesquad/secondhand/common/response/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/item/application/ItemService.java
  src/main/java/com/codesquad/secondhand/item/application/dto/MyTransactionResponse.java
  src/main/java/com/codesquad/secondhand/item/application/dto/MyTransactionSliceResponse.java
  src/main/java/com/codesquad/secondhand/item/infrastructure/ItemRepository.java
  src/main/java/com/codesquad/secondhand/user/ui/UserController.java
  src/test/java/com/codesquad/secondhand/acceptance/UserAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/fixture/ItemFixture.java
  src/test/java/com/codesquad/secondhand/util/steps/UserSteps.java
Labels: feature, SPRINT#3

#44 feat/#41 이미지 업로드 기능 구현
  src/main/java/com/codesquad/secondhand/Image/application/dto/ImageResponse.java
  src/main/java/com/codesquad/secondhand/Image/application/dto/ImageUploadRequest.java
  src/main/java/com/codesquad/secondhand/Image/domain/Image.java
  src/main/java/com/codesquad/secondhand/Image/domain/ImageFileDetail.java
  src/main/java/com/codesquad/secondhand/Image/persentation/ImageController.java
  src/main/java/com/codesquad/secondhand/auth/presentation/AuthController.java
  src/main/java/com/codesquad/secondhand/category/presentation/CategoryController.java
  src/main/java/com/codesquad/secondhand/common/response/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/item/domain/Item.java
  src/main/java/com/codesquad/secondhand/item/infrastructure/ItemCustomRepository.java
  src/main/java/com/codesquad/secondhand/item/infrastructure/ItemCustomRepositoryImpl.java
  src/main/java/com/codesquad/secondhand/item/infrastructure/ItemRepository.java
  src/main/java/com/codesquad/secondhand/item/presentation/ItemController.java
  src/main/java/com/codesquad/secondhand/region/presentation/RegionController.java
  src/main/java/com/codesquad/secondhand/user/domain/User.java
  src/main/java/com/codesquad/secondhand/user/presentation/UserController.java
  src/test/java/com/codesquad/secondhand/acceptance/AuthAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/acceptance/CategoryAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/acceptance/ImageAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/acceptance/RegionAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/acceptance/UserAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/AcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/DatabaseLoader.java
  src/test/java/com/codesquad/secondhand/util/fixture/ImageFixture.java
  src/test/java/com/codesquad/secondhand/util/steps/ImageSteps.java
Labels: feature, SPRINT#3

#46 feat #45: 상품 상태 수정 기능 구현
  src/main/java/com/codesquad/secondhand/common/exception/ErrorType.java
  src/main/java/com/codesquad/secondhand/common/exception/item/ItemUnauthorizedUpdateException.java
  src/main/java/com/codesquad/secondhand/item/application/ItemService.java
  src/main/java/com/codesquad/secondhand/item/application/dto/ItemUpdateStatusRequest.java
  src/main/java/com/codesquad/secondhand/item/application/dto/ItemUpdateStatusResponse.java
  src/main/java/com/codesquad/secondhand/item/domain/Item.java
  src/main/java/com/codesquad/secondhand/item/presentation/ItemController.java
  src/test/java/com/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/steps/ItemSteps.java
Labels: feature, SPRINT#3

#63 fix #62: 상품 생성 및 상품 상세 조회 응답 객체 수정
  src/main/java/com/codesquad/secondhand/category/application/dto/CategoryItemDetailResponse.java
  src/main/java/com/codesquad/secondhand/item/application/ItemFacade.java
  src/main/java/com/codesquad/secondhand/item/application/ItemService.java
  src/main/java/com/codesquad/secondhand/item/application/dto/ItemCreateResponse.java
  src/main/java/com/codesquad/secondhand/item/application/dto/ItemDetailResponse.java
  src/main/java/com/codesquad/secondhand/item/presentation/ItemController.java
  src/test/java/com/codesquad/secondhand/acceptance/UserAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/fixture/CategoryFixture.java
Labels: fix, SPRINT#5

#65 Fix/#64 관심 내역, 판매 내역, 상품 내역 응답 수정
  build.gradle
  src/main/java/com/codesquad/secondhand/category/application/dto/CategoryInfoResponse.java
  src/main/java/com/codesquad/secondhand/item/application/dto/ItemDetailResponse.java
  src/main/java/com/codesquad/secondhand/item/application/dto/ItemSliceResponse.java
  src/main/java/com/codesquad/secondhand/item/application/dto/MyTransactionResponse.java
  src/main/java/com/codesquad/secondhand/item/application/dto/MyTransactionSliceResponse.java
  src/main/java/com/codesquad/secondhand/user/application/dto/MyWishlistSliceResponse.java
  src/test/java/com/codesquad/secondhand/util/fixture/CategoryFixture.java
  src/test/java/com/codesquad/secondhand/util/fixture/ItemFixture.java
  src/test/java/com/codesquad/secondhand/util/fixture/UserFixture.java
Labels: fix, SPRINT#5

#70 feat/#69 관심목록 카테고리 조회 기능 구현
  src/main/java/com/codesquad/secondhand/auth/application/AuthFacade.java
  src/main/java/com/codesquad/secondhand/category/application/CategoryService.java
  src/main/java/com/codesquad/secondhand/category/application/dto/CategoriesInfoResponse.java
  src/main/java/com/codesquad/secondhand/category/application/dto/CategoryInfoResponse.java
  src/main/java/com/codesquad/secondhand/category/infrastructure/CategoryRepository.java
  src/main/java/com/codesquad/secondhand/common/response/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/item/application/ItemFacade.java
  src/main/java/com/codesquad/secondhand/item/application/dto/ItemCreateRequest.java
  src/main/java/com/codesquad/secondhand/item/domain/Item.java
  src/main/java/com/codesquad/secondhand/item/domain/StatusType.java
  src/main/java/com/codesquad/secondhand/item/presentation/ItemController.java
  src/main/java/com/codesquad/secondhand/region/domain/Region.java
  src/main/java/com/codesquad/secondhand/user/application/UserFacade.java
  src/main/java/com/codesquad/secondhand/user/domain/MyWishlists.java
  src/main/java/com/codesquad/secondhand/user/domain/User.java
  src/main/java/com/codesquad/secondhand/user/domain/Wishlist.java
  src/main/java/com/codesquad/secondhand/user/presentation/UserController.java
  src/test/java/com/codesquad/secondhand/acceptance/UserAcceptanceTest.java
  src/test/java/com/codesquad/secondhand/util/steps/UserSteps.java
Labels: feature, SPRINT#5

#72 fix #71: 조회 수 증가 시 업데이트 날짜 변경되는 버그 수정
  .github/workflows/cicd.yml
  src/main/java/com/codesquad/secondhand/common/exception/item/ItemImageEmptyException.java
  src/main/java/com/codesquad/secondhand/item/application/ItemService.java
  src/main/java/com/codesquad/secondhand/item/domain/Item.java
  src/main/java/com/codesquad/secondhand/item/infrastructure/ItemRepository.java
Labels: fix, SPRINT#5
